db:
  build: dockerfiles/db
  ports:
    - "5432"
  volumes:
    - /var/lib/postgresql

app:
  build: dockerfiles/app
  command: bash -c "sleep 2 && make run"
  external_links:
    - locusttestapi_db_1:db
  ports:
    - "8000:8000"
  volumes:
    - ./app:/home/ubuntu/app/
  working_dir: /home/ubuntu/app/

test_coverage:
  build: dockerfiles/app
  command: bash -c "sleep 2 && make test"
  external_links:
    - locusttestapi_db_1:db
  ports:
    - "8000:8000"
  volumes:
    - ./app:/home/ubuntu/app/
  working_dir: /home/ubuntu/app/

locust:
  build: dockerfiles/locust
  command: locust -f main.py
  external_links:
    - locusttestapi_app_1:app
  ports:
    - "8089:8089"
  volumes:
    - ./locust:/home/ubuntu/locust
  working_dir: /home/ubuntu/locust
