db:
  build: dockerfiles/db
  ports:
    - "5432"
  volumes:
    - /var/lib/postgresql

web:
  build: dockerfiles/app
  command: make run
  links:
    - db
  ports:
    - "8000:8000"
  volumes:
    - app:/home/ubuntu/app/
  working_dir: /home/ubuntu/app/
